- hosts: server
  user: zoadmin
  become: yes
  vars:
    wr_repo: 'https://github.com/webrecorder/webrecorder'
    wr_dir: /opt/webrecorder
    wr_app_host: 'cats-dev01.cats.uni-heidelberg.de'
    wr_content_host: '{{ wr_app_host }}'

    wr_remote_browsers:
      - 'chrome:53'
      - 'firefox:49'

    cert_key_name: '{{ wr_app_host }}'

    nginx_conf_template: "{{ playbook_dir }}/templates/nginx.conf"
    nginx_vhost_template: "{{ playbook_dir }}/templates/wrhost.conf"
    nginx_remove_default_vhost: true

    nginx_vhosts:
      - server_name: "{{ wr_content_host }}"
        filename: "{{ wr_content_host }}"
        include_ws: false

      - server_name: "{{ wr_app_host }}"
        filename: "{{ wr_app_host }}"
        include_ws: true
    pip_package: python3-pip
    pip_install_packages:
      - name: docker-compose
      - name: docker

  roles:
    - { role: geerlingguy.pip, become: true, become_user: root }
    - { role: nginx, become: true, become_user: root, when: "wr_app_host != ''" }
   # - { role: dehydrated, become: true, become_user: root, when: "wr_app_host != ''" }
    - { role: geerlingguy.docker, become: true, become_user: root }
    - { role: webrecorder_init }

